### ISSUE TITLE
Implement data checks for invalid websites 404 error

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-map-backend#4]
This is an enhancement request for data presented on https://map.schnelltestportal.de/

## Issue

Some test stations present a URL under "Infos & Termin" which does not work.

## Suggested enhancement

Regularly check that all URLs are functioning and resolve any which are not.

## Example

https://map.schnelltestportal.de/api/centers?latne=48.13644999876734&lngne=11.584551160296831&latsw=48.13352506185528&lngsw=11.579905574283037&dcc=true

```
{
    "centers": [
        {
            "uuid": "edf10170-c64d-11ec-aa9f-0a580a82360d",
            "name": "Isartor - München",
            "email": "support@vitolus.de",
            "website": "https://www.vitotest.de/isartor",
            "coordinates": {
                "longitude": 11.5820649,
                "latitude": 48.1351013
            },
            "logo": null,
            "marker": null,
            "address": "Thomas-Wimmer-Ring 1 - 3, 80539 München",
            "openingHours": [
                "Mo - Sa: 07:30 - 11:00 & 11:45 - 16:30"
            ],
            "addressNote": null,
            "appointment": "Possible",
            "testKinds": [
                "Antigen",
                "PCR"
            ],
            "dcc": true
        }
    ]
}

```

https://www.vitotest.de/isartor gives 
```
404
This page could not be found.
```

**Comment by MikeMcC399** [comment]
The problem still exists for the example testing station.

**Comment by dreske** [comment]
Will bring it up.

Mike McCready ***@***.***> schrieb am Do., 18. Aug. 2022,
18:04:
